version: 2

builds:
  - id: webdav-s3
    main: ./cmd/webdav-s3
    binary: webdav-s3
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - webdav-s3
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE*
      - .env.example

checksums:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'
