name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.x'
          check-latest: true
          cache: true

      - name: Tidy
        run: go mod tidy

      - name: Build (cmd/webdav-s3)
        run: go build -v ./cmd/webdav-s3

#      - name: Test
#        run: go test ./...
